#!/bin/sh /etc/rc.common
#  ────────────────────────────────────────────────────────────
#                     ╔╗  ╔╗ ╔══╗      ╔════╗
#                     ║╚╗╔╝║ ╚╣╠╝      ║╔╗╔╗║
#                     ╚╗╚╝╔╝  ║║  ╔══╗ ╚╝║║╚╝
#                      ╚╗╔╝   ║║  ║╔╗║   ║║
#                       ║║   ╔╣╠╗ ║╚╝║   ║║
#                       ╚╝   ╚══╝ ╚══╝   ╚╝
#    ╔╗╔═╗                    ╔╗                     ╔╗
#    ║║║╔╝                   ╔╝╚╗                    ║║
#    ║╚╝╝  ╔══╗ ╔══╗ ╔══╗  ╔╗╚╗╔╝  ╔══╗ ╔╗ ╔╗╔╗ ╔══╗ ║║  ╔══╗
#    ║╔╗║  ║║═╣ ║║═╣ ║╔╗║  ╠╣ ║║   ║ ═╣ ╠╣ ║╚╝║ ║╔╗║ ║║  ║║═╣
#    ║║║╚╗ ║║═╣ ║║═╣ ║╚╝║  ║║ ║╚╗  ╠═ ║ ║║ ║║║║ ║╚╝║ ║╚╗ ║║═╣
#    ╚╝╚═╝ ╚══╝ ╚══╝ ║╔═╝  ╚╝ ╚═╝  ╚══╝ ╚╝ ╚╩╩╝ ║╔═╝ ╚═╝ ╚══╝
#                    ║║                         ║║
#                    ╚╝                         ╚╝
#
#    Lead Maintainer: Roman Kutashenko <kutashenko@gmail.com>
#  ────────────────────────────────────────────────────────────

DOCKER_BIN="/usr/bin/docker"
DOCKER_CONTAINER_MQTT_NAME="mosquitto"
DOCKER_CONTAINER_UI_NAME="cedalo"
DOCKER_IMAGE_MQTT="$(cat /images/mosquitto)"
DOCKER_IMAGE_UI="$(cat /images/cedalo)"

START=99
USE_PROCD=1

start_service() {
    #
    #   Prepare config
    #
    config_load mqtt

    #
    #   Check if we have start MQTT
    #
    config_get activate params activate
    if [ "${activate}" != "1" ]; then
        exit 0
    fi

    #
    #   Prepare data folder
    #
    config_get data_path params data_path
    if [ ! -f "${data_path}/data" ]; then
        mkdir -p "${data_path}/data"

        config_get mosquitto_config params mosquitto_config
        echo "${mosquitto_config}" | base64 -d > ${data_path}/mosquitto.conf 
        
        config_get mosquitto_sequrity params mosquitto_sequrity
        echo "${mosquitto_sequrity}"  | base64 -d > ${data_path}/data/dynamic-security.json

        chown -R 1000:1000 "${data_path}"
    fi

    #
    #   Load Mosquitto if not present
    #
    LOADED_VERSION="$(${DOCKER_BIN} image list | grep 7 | tail -1 | awk '{print $1 ":" $2}')"
    if [ "${LOADED_VERSION}" != "${DOCKER_IMAGE_MQTT}" ]; then
        cat "/images/mosquitto.tar" | ${DOCKER_BIN} load 
    fi

    #
    #   Load Cedalo if not present
    #
    LOADED_VERSION="$(${DOCKER_BIN} image list | grep 7 | tail -1 | awk '{print $1 ":" $2}')"
    if [ "${LOADED_VERSION}" != "${DOCKER_IMAGE_UI}" ]; then
        cat "/images/cedalo.tar" | ${DOCKER_BIN} load 
    fi

    #
    #   Parameters
    #
    config_get host_network params host_network
    config_get lang params lang
    config_get host_network params host_network
    if [ "${host_network}" == "1" ]; then
        NETWORK_TYPE="--network host"
    fi
  
    #
    #   Create Procd instance
    #
    echo "Starting Rhasspy"
    procd_open_instance
    procd_set_param respawn
    procd_set_param file /etc/config/mqtt
    procd_set_param command "${DOCKER_BIN}" run -d --rm --name "${DOCKER_CONTAINER_MQTT_NAME}" \
        ${NETWORK_TYPE} \
        -v "${data_path}":/mosquitto/config \
        ${DOCKER_IMAGE_MQTT} ; \
        "${DOCKER_BIN}" run -d --rm --name "${DOCKER_CONTAINER_UI_NAME}" \
        ${NETWORK_TYPE} \
        -e CEDALO_MC_BROKER_ID= "Mosquitto 2.0" \
        -e CEDALO_MC_BROKER_URL="mqtt://127.0.0.1:1883" \
        -e CEDALO_MC_BROKER_USERNAME="${cedalo_broker_username}" \
        -e CEDALO_MC_BROKER_PASSWORD="${cedalo_broker_username}" \
        -e CEDALO_MC_USERNAME="${cedalo_mc_username}" \
        -e ServiceName="${cedalo_mc_password}" \
        ${DOCKER_IMAGE_UI};

    procd_close_instance
}
