#  ────────────────────────────────────────────────────────────
#                     ╔╗  ╔╗ ╔══╗      ╔════╗
#                     ║╚╗╔╝║ ╚╣╠╝      ║╔╗╔╗║
#                     ╚╗╚╝╔╝  ║║  ╔══╗ ╚╝║║╚╝
#                      ╚╗╔╝   ║║  ║╔╗║   ║║
#                       ║║   ╔╣╠╗ ║╚╝║   ║║
#                       ╚╝   ╚══╝ ╚══╝   ╚╝
#    ╔╗╔═╗                    ╔╗                     ╔╗
#    ║║║╔╝                   ╔╝╚╗                    ║║
#    ║╚╝╝  ╔══╗ ╔══╗ ╔══╗  ╔╗╚╗╔╝  ╔══╗ ╔╗ ╔╗╔╗ ╔══╗ ║║  ╔══╗
#    ║╔╗║  ║║═╣ ║║═╣ ║╔╗║  ╠╣ ║║   ║ ═╣ ╠╣ ║╚╝║ ║╔╗║ ║║  ║║═╣
#    ║║║╚╗ ║║═╣ ║║═╣ ║╚╝║  ║║ ║╚╗  ╠═ ║ ║║ ║║║║ ║╚╝║ ║╚╗ ║║═╣
#    ╚╝╚═╝ ╚══╝ ╚══╝ ║╔═╝  ╚╝ ╚═╝  ╚══╝ ╚╝ ╚╩╩╝ ║╔═╝ ╚═╝ ╚══╝
#                    ║║                         ║║
#                    ╚╝                         ╚╝
#
#    Lead Maintainer: Roman Kutashenko <kutashenko@gmail.com>
#  ────────────────────────────────────────────────────────────

#
#   CentOS 8.4
#
FROM centos:centos8.4.2105

LABEL maintainer="yiot" name="CV-2SE build" vendor="yiot" license="GPLv2" build-date="{{ BUILDDATE }}" version="{{ IMGVERS1 }}"

#
#   Time zone
#
ENV TZ=Europe/Sofia
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#
#   Install packages
#
RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* &&\
    yum -y install dnf-plugins-core &&\
    yum config-manager --set-enabled powertools &&\
    yum clean all &&\
    yum -y update &&\
    yum -y install epel-release &&\
    yum -y install asciidoc autoconf automake bash binutils bison bzip2 cmake ccache curl-devel diffutils dos2unix expat-devel \
           findutils flex gawk gcc gcc-c++ gettext git glibc-headers gmp-devel intltool kernel-devel kernel-headers lcov \
           libcurl-devel libmpc-devel libtool libusb libxml2-devel make mpfr-devel ncurses-devel openssl \
           openssl-devel patch patchutils perl-ExtUtils-MakeMaker subversion sudo unzip util-linux valgrind wget \
    which zlib zlib-devel curl mercurial bubblewrap file mc rsync python3 python3-distutils-extra genisoimage libstdc++-static \
    qemu-img elfutils-libelf-devel && \
    yum -y clean all

#
#   Add Flutter
#
ADD flutter /usr/local/flutter


#
#   Entrypoint
#
ADD entrypoint.sh /usr/local/bin/
ADD started.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/started.sh /usr/local/bin/entrypoint.sh
CMD ["/usr/local/bin/entrypoint.sh"]
