#!/bin/sh

# WAN
uci set network.wan.device='eth0'
uci set network.wan6.device='eth0'

# LAN
uci set network.lan.proto='static'
uci set network.lan.ipaddr='10.0.100.1'
uci set network.lan.netmask='255.255.255.0'
uci del network.@device[0].ports
uci add_list network.@device[0].ports='eth1'

# WiFi
uci set wireless.radio0.htmode='HT20'
uci set wireless.radio0.band='2g'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.cell_density='0'
uci set wireless.default_radio0.ssid='Danko'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='yiotDanko'
uci del wireless.default_radio0.disabled
uci del wireless.radio0.disabled

# Set Host Name
uci set system.@system[0].hostname="danko"

# Switch to HTTP // TODO: remove it
uci delete nginx._redirect2ssl
uci delete nginx._lan.uci_manage_ssl
uci delete nginx._lan.ssl_certificate
uci delete nginx._lan.ssl_certificate_key
uci delete nginx._lan.ssl_session_cache
uci delete nginx._lan.ssl_session_timeout
uci set nginx._lan.listen='80 default_server'

uci commit


exit 0